project:
  type: website
  output-dir: docs

website:
  title: "esqLABSRShiny"
  navbar:
    collapse-below: lg
    background: primary
    left:
      - text: "Package Review"
        href: review.qmd
      - text: "Proposals"
        href: proposals.qmd
      - text: "Roadmap"
        href: roadmap.qmd
      # - sidebar:review
      # - sidebar:proposals
      # - sidebar:roadmap
      
  sidebar:
    - id: review
      # title: "Review Summary"
      style: "docked"
      contents:
        - text: "Review Summary"
          href: review.qmd
        - text: "Installation"
          href: test_install.qmd
        - text: "User Experience"
          href: test_use.qmd
        - text: "Model Settings"
          href: test_data.qmd
        - text: "Vis' & Reporting"
          href: test_visualize.qmd
    # - id: proposals
    #   title: "Proposals"
    #   contents:
    #     - proposals.qmd
    # - id: roadmap
    #   title: "Roadmap"
    #   contents:
    #     - roadmap.qmd

execute: 
  freeze: auto

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



